import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import styles from './styles.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.RootLayout}`}>
        <div className={styles.Navbar}>
          RootLayout
          <Link href="/">Go to /d</Link>
          <Link href="/a">Go to /a</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
